import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/organisms/Navbar";
import Footer from "./components/organisms/Footer";
import { Ubuntu_Sans } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ubuntuFont = Ubuntu_Sans({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntuFont.className} bg-background text-foreground py-20 flex flex-col justify-between`}
      >
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
