import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/organisms/Navbar";
import Footer from "@/components/organisms/Footer";
import { Ubuntu_Sans } from "next/font/google";
import SplitWhite from "@/components/atoms/SplitWhite";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ubuntuFont = Ubuntu_Sans({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntuFont.className} bg-background text-foreground flex flex-col justify-between min-h-screen`}
      >
        <Navbar></Navbar>
        <div className="relative flex min-h-screen justify-between w-full p-12">
          {" "}
          {children}
        </div>
        <Footer></Footer>
      </body>
    </html>
  );
}
